# General Jekyll Config
pygments: true
url: cedced19.github.io
lsi: false
exclude: [ README.md]
markdown: kramdown
permalink: /blog/:year/:title/
timezone: Europe/Paris

#Other
title: Cedced19

#CSS Color
color: 27ae60
progressbar: acf3ca
link: 2ecc71
btn: 2ecc71
span: 2ecc71
selection: 2ecc71
