# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Cedced19
tagline:          'Developpeur'
description:      'Je suis le Créateur d Iced'
url:              http://cedced19.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/cedced19/cedced19.github.io
