# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

posts:
  en: Posts
  fr: Publications

description:
  en: "Cédric JUNG website."
  fr: "Site de Cédric JUNG."

keywords:
  en: Cédric, JUNG, Developer, Node, JS, HTML, CSS, JavaScript, Vosges, Phalsbourg, Bike, Centrale Lille
  fr: Cédric, JUNG, Developpeur, Node, JS, HTML, CSS, JavaScript, Vosges, Phalsbourg, Vélo, VTT, Cyclisme, Centrale Lille

footer_description:
  en:  "I love creating new things, walking in the forest, running and cross-country cycling."
  fr:  "J'adore inventer, marcher en forêt, courir et faire du VTT."

title: Cédric JUNG
author: Cédric JUNG
email: cedric@cedric-jung.eu

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cedric-jung.eu" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  cedced19

# Build settings
markdown: CommonMark
theme: minima
plugins:
  - jekyll-feed
  - jekyll-polyglot
  - octopress-minify-html
  - jekyll-assets

languages: ["en", "fr"]
default_lang: "en"
exclude_from_localization: ["assets"]
parallel_localization: true

languages_name:
  en: English
  fr: Français

exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor

assets:
  dirname: assets
  baseurl: /assets/
  cachebust: hard
  gzip: [ text/css ]
  assets:
    - "*.png"
    - "main.css"
  sources:
    - _assets/css
  compress:
    js:  true
    css: true
